services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: toolkeeper_db
      POSTGRES_USER: team8
      POSTGRES_PASSWORD: toolkeeper
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: toolkeeper.settings
      DB_NAME: toolkeeper_db
      DB_USER: team8
      DB_PASSWORD: toolkeeper
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/code
volumes:
  db-data:
