"""
Django settings for toolkeeper project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .settings_common import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [os.environ.get('ALLOWED_HOSTS')]

# STATIC_ROOT = '/code/static'
MEDIA_ROOT = '/code/media'

SERVICE_ACCOUNT_KEY_ROOT = f'/code/{SERVICE_ACCOUNT_KEY_NAME}'

# ロギング設定
LOGGING = {
    'version': 1, # 1固定
    'disable_existing_loggers': False,
    
    # ロガーの設定
    'loggers': {
        # Djangoが利用するロガー
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        # toolkeeper_appアプリケーションが利用するロガー
        'toolkeeper_app': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },

    # ハンドラの設定
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'prod'
        },
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.TimedRotaingFileHandler',
        #     'filename': os.path.join(BASE_DIR, 'logs/django.log'),
        #     'formatter': 'prod',
        #     'when': 'D',  # ログテーション（新しいファイルへの切り替え）間隔の単位（D=日）
        #     'interval': 1,  # ログテーション間隔（1日単位）
        #     'backupCount': 7,  # 保存しておくログファイル数
        # },
    },
    
    # フォーマッタの設定
    'formatters': {
        'prod': {
            'format': '\t'.join([
                '%(asctime)s',
                '[%(levelname)s]',
                '%(pathname)s(Line:%(lineno)d)',
                '%(message)s'
            ])
        },
    }
}
